name: colocalization-ensemble
dependencies:
  - plink2=2.00a2.3
  - snakemake=6.0.0
  - tabix=0.2.6

  - r-base=4.0.2
  - r-coloc=3.1
  - r-data.table=1.14.0
  - r-devtools=2.3.2
  - r-dplyr=1.0.4
  - r-ggplot2=3.3.3
  - r-ggrepel=0.9.1
  - r-glmnet=4.0_2
  - r-readr=1.4.0
  - r-reshape2=1.4.4
  - r-rsqlite=2.2.3
  - r-survey=4.0
  - r-tidyverse=1.3.0
  - bioconductor-qvalue=2.22.0

  - scikit-learn=0.24.1
  - scipy=1.5.3
  - pandas=1.2.3
  - progress=1.5
