name: coloc_wrapper
dependencies:
  - plink2=1.90b3.35
  - tabix=0.2.6

  - r-base=4.0.2
  - r-coloc
  - r-readr
  - r-dplyr
  - r-ggplot2
  - r-ggrepel
  - r-locuscomparer
  - r-tidyverse
  - r-gsmr
  - r-survey
  - r-data.table
  - r-glmnet
  - r-reshape2
  - r-methods
  - r-RSQLite

  - python=3.6
  - progress
  - pandas
