name: coloc_wrapper
dependencies:
  - plink2=1.90b3.35
  - tabix=0.2.6
  - snakemake=5.24.2

  - r-base=4.0.2
  - r-coloc
  - r-readr
  - r-dplyr
  - r-ggplot2
  - r-ggrepel
  - r-tidyverse
  - r-survey
  - r-data.table
  - r-glmnet
  - r-reshape2
  - r-RSQLite
  - r-devtools
  - bioconductor-qvalue

  - python=3.6
  - progress
  - pandas
  - scipy
  - scikit-learn
